version: "3.9"

services:
  db:
    image: postgres:15
    container_name: amilate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amilate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: amilate_app
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/amilate?sslmode=disable
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/backend
    command: ["go", "run", "cmd/server/main.go"]

volumes:
  db_data: