// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	model "github.com/iacopoGhilardi/amILate/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AppointmentServiceInterface is an autogenerated mock type for the AppointmentServiceInterface type
type AppointmentServiceInterface struct {
	mock.Mock
}

// CreateAppointment provides a mock function with given fields: a
func (_m *AppointmentServiceInterface) CreateAppointment(a *model.Appointment) (*model.Appointment, error) {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 *model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Appointment) (*model.Appointment, error)); ok {
		return rf(a)
	}
	if rf, ok := ret.Get(0).(func(*model.Appointment) *model.Appointment); ok {
		r0 = rf(a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Appointment) error); ok {
		r1 = rf(a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAppointment provides a mock function with given fields: id
func (_m *AppointmentServiceInterface) DeleteAppointment(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppointment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAppointmentFromPublicId provides a mock function with given fields: publicId
func (_m *AppointmentServiceInterface) DeleteAppointmentFromPublicId(publicId uuid.UUID) error {
	ret := _m.Called(publicId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppointmentFromPublicId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(publicId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAppointments provides a mock function with no fields
func (_m *AppointmentServiceInterface) GetAllAppointments() ([]model.Appointment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAppointments")
	}

	var r0 []model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Appointment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Appointment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAppointmentByID provides a mock function with given fields: id
func (_m *AppointmentServiceInterface) GetAppointmentByID(id uint) (*model.Appointment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentByID")
	}

	var r0 *model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Appointment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Appointment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAppointmentByPublicId provides a mock function with given fields: _a0
func (_m *AppointmentServiceInterface) GetAppointmentByPublicId(_a0 uuid.UUID) (*model.Appointment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentByPublicId")
	}

	var r0 *model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Appointment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Appointment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppointmentServiceInterface creates a new instance of AppointmentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentServiceInterface {
	mock := &AppointmentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
