// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	model "github.com/iacopoGhilardi/amILate/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AppointmentRepositoryInterface is an autogenerated mock type for the AppointmentRepositoryInterface type
type AppointmentRepositoryInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *AppointmentRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *AppointmentRepositoryInterface) Find(id uint) (*model.Appointment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Appointment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Appointment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with no fields
func (_m *AppointmentRepositoryInterface) FindAll() ([]model.Appointment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Appointment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Appointment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPublicId provides a mock function with given fields: publicId
func (_m *AppointmentRepositoryInterface) FindByPublicId(publicId uuid.UUID) (*model.Appointment, error) {
	ret := _m.Called(publicId)

	if len(ret) == 0 {
		panic("no return value specified for FindByPublicId")
	}

	var r0 *model.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Appointment, error)); ok {
		return rf(publicId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Appointment); ok {
		r0 = rf(publicId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(publicId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: entity
func (_m *AppointmentRepositoryInterface) Save(entity *model.Appointment) error {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Appointment) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAppointmentRepositoryInterface creates a new instance of AppointmentRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentRepositoryInterface {
	mock := &AppointmentRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
