// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "github.com/iacopoGhilardi/amILate/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// AuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type AuthServiceInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: loginDto
func (_m *AuthServiceInterface) Login(loginDto dto.LoginDto) (*dto.LoginResponseDto, error) {
	ret := _m.Called(loginDto)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.LoginResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.LoginDto) (*dto.LoginResponseDto, error)); ok {
		return rf(loginDto)
	}
	if rf, ok := ret.Get(0).(func(dto.LoginDto) *dto.LoginResponseDto); ok {
		r0 = rf(loginDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.LoginDto) error); ok {
		r1 = rf(loginDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: registerDto
func (_m *AuthServiceInterface) Register(registerDto dto.RegistrationDto) (*dto.LoginResponseDto, error) {
	ret := _m.Called(registerDto)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.LoginResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.RegistrationDto) (*dto.LoginResponseDto, error)); ok {
		return rf(registerDto)
	}
	if rf, ok := ret.Get(0).(func(dto.RegistrationDto) *dto.LoginResponseDto); ok {
		r0 = rf(registerDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.RegistrationDto) error); ok {
		r1 = rf(registerDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthServiceInterface creates a new instance of AuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceInterface {
	mock := &AuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
