// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BaseRepositoryInterface is an autogenerated mock type for the BaseRepositoryInterface type
type BaseRepositoryInterface[T interface{}] struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *BaseRepositoryInterface[T]) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *BaseRepositoryInterface[T]) Find(id uint) (*T, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*T, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *T); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with no fields
func (_m *BaseRepositoryInterface[T]) FindAll() ([]T, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]T, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: entity
func (_m *BaseRepositoryInterface[T]) Save(entity *T) error {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*T) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBaseRepositoryInterface creates a new instance of BaseRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseRepositoryInterface[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseRepositoryInterface[T] {
	mock := &BaseRepositoryInterface[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
