// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/iacopoGhilardi/amILate/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// DestinationRepositoryInterface is an autogenerated mock type for the DestinationRepositoryInterface type
type DestinationRepositoryInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *DestinationRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *DestinationRepositoryInterface) Find(id uint) (*model.Destination, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.Destination
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Destination, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Destination); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Destination)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with no fields
func (_m *DestinationRepositoryInterface) FindAll() ([]model.Destination, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Destination
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Destination, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Destination); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Destination)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: entity
func (_m *DestinationRepositoryInterface) Save(entity *model.Destination) error {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Destination) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDestinationRepositoryInterface creates a new instance of DestinationRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDestinationRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DestinationRepositoryInterface {
	mock := &DestinationRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
