// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/iacopoGhilardi/amILate/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// DestinationServiceInterface is an autogenerated mock type for the DestinationServiceInterface type
type DestinationServiceInterface struct {
	mock.Mock
}

// CreateDestination provides a mock function with given fields: d
func (_m *DestinationServiceInterface) CreateDestination(d *model.Destination) (*model.Destination, error) {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDestination")
	}

	var r0 *model.Destination
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Destination) (*model.Destination, error)); ok {
		return rf(d)
	}
	if rf, ok := ret.Get(0).(func(*model.Destination) *model.Destination); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Destination)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Destination) error); ok {
		r1 = rf(d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDestination provides a mock function with given fields: id
func (_m *DestinationServiceInterface) DeleteDestination(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDestination")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllDestinations provides a mock function with no fields
func (_m *DestinationServiceInterface) GetAllDestinations() ([]model.Destination, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllDestinations")
	}

	var r0 []model.Destination
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Destination, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Destination); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Destination)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDestinationByID provides a mock function with given fields: id
func (_m *DestinationServiceInterface) GetDestinationByID(id uint) (*model.Destination, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDestinationByID")
	}

	var r0 *model.Destination
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Destination, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Destination); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Destination)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDestinationServiceInterface creates a new instance of DestinationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDestinationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DestinationServiceInterface {
	mock := &DestinationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
